# Generated by Django 3.2.3 on 2021-05-24 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Priorities',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=160)),
                ('completed', models.BooleanField()),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.priorities')),
            ],
        ),
    ]
